include:
  - local: '/.gitlab/ci/terraform.yml'
  - local: '/.gitlab/ci/ansible.yml'
  # - local: '/.gitlab/ci/k8s.yml'


stages:
  - validate
  - plan
  - destroy
  - apply
  - provision
  - terratest

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

variables:
  OPERATION:
    description: "Select CI/CD-operation"
    value: "terraform"
    options:
      - "terraform"
      - "ansible"
      - "k8s"