apiVersion: v2
name: infra

version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: 0.1.0
  - name: mongodb
    version: 0.1.
    

dependencies:
  - name: infra
    version: 0.1.0