global:
  imageRegistry: "lakenotocean" 
  imagePullPolicy: Always

  postgresDbName: "store"
  postgresUser: "store"
  postgresPassword: "storepassword"
  postgresPort: "5432"

  mongoRootUser: "root"
  mongoRootPassword: "rootpassword"
  mongoPort: "27017"

  reportDbName: "sausage-store"
  reportDbUser: "report_user"
  reportDbPassword: "report_pass"
  ###vault:
  ###  enabled:false
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


backend:
  image:
    repository: ""
    name: sausage-backend
    tag: latest

backend-report:
  image:
    repository: ""
    name: sausage-backend-report
    tag: latest

frontend:
  image:
    repository: ""
    name: sausage-frontend
    tag: latest

infra:
  postgresql:
    storage: 2Gi
    storageClassName: "yc-network-hdd"
  mongodb:
    storage: 1Gi
    storageClassName: "yc-network-hdd"