# аннотации Pormetheus
annotations:
  path: /actuator/prometheus
  port: "8080"
  scrape: "true"

# пути артефактов
env:
  reportPath: "/logs/reports"
  logPath: "/logs"

# порты контейнера
service:
  port: 8080
containerPort: 8080

# стратегия репликации
revisionHistoryLimit: 15
replicas: 1
strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

# данные образа
image:
  repository: "lakenotocean" 
  name: sausage-backend
  tag: latest
imagePullPolicy: Always

# запрос ресурсов
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "1"

# проверка
livenessProbe:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 10
  periodSeconds: 15
readinessProbe:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 5
  periodSeconds: 10

# vpa 
vpa:
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: backend
      controlledResources: ["cpu", "memory"]