---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.imageRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }} 
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.containerPort }}
          volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
            mountPath: /etc/nginx/{{ .Values.nginxConf }}
            subPath: {{ .Values.nginxConf }}
            readOnly: true
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
          items:
            - key: {{ .Values.nginxConf }}
              path: {{ .Values.nginxConf }} 