apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mongodb-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300   # Автоочистка через 5 минут после завершения
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb-init
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: waiting
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Release.Name }}-mongodb-service {{ .Values.global.mongoPort }}; do
                echo "Waiting for MongoDB..."
                sleep 3
              done
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
      containers:
        - name: mongodb-init
          image: "mongo:7.0" 
          command:
            - mongosh
          args:
            - --host
            - {{ .Release.Name }}-mongodb-service
            - --port
            - "{{ .Values.global.mongoPort }}"
            - --username
            - "$(MONGO_INITDB_ROOT_USERNAME)"
            - --password
            - "$(MONGO_INITDB_ROOT_PASSWORD)"
            - --authenticationDatabase
            - admin
            - --eval
            - |
              db = db.getSiblingDB('{{ .Values.global.reportDbName }}');
              if (!db.getUser('{{ .Values.global.reportDbUser }}')) {
                db.createUser({
                  user: '{{ .Values.global.reportDbUser }}',
                  pwd: '{{ .Values.global.reportDbPassword }}',
                  roles: [{ role: 'readWrite', db: '{{ .Values.global.reportDbName }}' }]
                });
                print('User {{ .Values.global.reportDbUser }} created successfully.');
              } else {
                print('User {{ .Values.global.reportDbUser }} already exists.');
              }
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"