---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.mongoPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}