# порты контейнера
service:
  port: 80
containerPort: 8080

# стратегии репликации
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: Recreate

# данные образа
image:
  repository: "lakenotocean" 
  name: sausage-frontend
  tag: latest

# сеть
ingress:
  host: front-s18727602.students-projects.ru
  path: /
  pathType: Prefix
  tlsSecret: 2sem-students-projects-wildcard-secret

# запрос ресурсов
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "64Mi"
    cpu: "100m"
nginxConf: nginx.conf