-- Создание начальных таблиц

-- создание таблицы продуктов
CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    picture_url character varying(255)
);

-- создание таблицы с информацией по продуктам
CREATE TABLE IF NOT EXISTS public.product_info
(
    product_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    price double precision
);

-- создание таблицы заказов
CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status character varying(255)
);

-- создание таблицы с информацией о времени создания заказов
CREATE TABLE IF NOT EXISTS public.orders_date
(
    order_id bigint NOT NULL,
    status character varying(255),
    date_created date DEFAULT CURRENT_DATE
);

-- создание связующей таблицы прдуктов и заказов
CREATE TABLE IF NOT EXISTS public.order_product
(
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);
