# порты контейнера
env:
  port: "8080"  
containerPort: 8080

# стратегии репликации
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: Recreate

# данные образа
image:
  repository: "lakenotocean"
  name: sausage-backend-report
  tag: latest

# запрос ресурсов
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "200m"

# проверка
livenessProbe:
  enabled: true
  path: /api/v1/health
  initialDelaySeconds: 10
  periodSeconds: 15
readinessProbe:
  enabled: true
  path: /api/v1/health
  initialDelaySeconds: 5
  periodSeconds: 10

# hpa
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80