image: YOUR_DOCKERHUB/sausage-backend-report:latest
containerPort: 8080
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: Recreate
image:
  repository: ""
  name: sausage-backend-report
  tag: latest
env:
  port: "8080"  
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"
livenessProbe:
  enabled: true
  path: /api/v1/health
  initialDelaySeconds: 10
  periodSeconds: 15
readinessProbe:
  enabled: true
  path: /api/v1/health
  initialDelaySeconds: 5
  periodSeconds: 10
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80