---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage | default "2Gi" }}
  {{- with .Values.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}