apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
stringData:
  DB: mongodb://{{ .Values.global.reportDbUser }}:{{ .Values.global.reportDbPassword }}@{{ .Release.Name }}-mongodb-service:{{ .Values.global.mongoPort }}/{{ .Values.global.reportDbName }}