---
vault_container_name: vault
vault_image: "hashicorp/vault:1.17.6"
vault_config_dir: /etc/vault.d
vault_data_dir: /opt/vault/data
vault_port: 8200

# токен, root по умолчанию
vault_dev_root_token_id: "{{ lookup('env', 'VAULT_DEV_ROOT_TOKEN_ID') | default('root', true) }}"

# секреты приложений
vault_kv_path: secret
vault_secret_path: sausage-store
vault_secrets:
  spring.datasource.username: "{{ lookup('env', 'VAULT_SPRING_DATASOURCE_USERNAME') }}"
  spring.datasource.password: "{{ lookup('env', 'VAULT_SPRING_DATASOURCE_PASSWORD') }}"
  spring.data.mongodb.uri: "{{ lookup('env', 'VAULT_SPRING_DATA_MONGODB_URI') }}"
  postgresUser: "{{ lookup('env', 'VAULT_SPRING_DATASOURCE_USERNAME') }}"
  postgresPassword: "{{ lookup('env', 'VAULT_SPRING_DATASOURCE_PASSWORD') }}"
  # здесь просто переменные по умолчанию 
  mongoRootUser: "{{ lookup('env', 'VAULT_MONGO_ROOT_USER') | default('root', true) }}"
  mongoRootPassword: "{{ lookup('env', 'VAULT_MONGO_ROOT_PASSWORD') | default('rootpassword', true) }}"
  reportDbUser: "{{ lookup('env', 'VAULT_REPORT_DB_USER') | default('report_user', true) }}"
  reportDbPassword: "{{ lookup('env', 'VAULT_REPORT_DB_PASSWORD') | default('report_pass', true) }}"